### ISSUE TITLE
Connect this and curseforge

### ISSUE THREAD

**Issue by Christofmeg** [Viola-Siemens/OceanWorld#1]
Can you add this repo as a source to your CurseForge page?

Go to https://www.curseforge.com/minecraft/mc-mods/ocean-world/settings/source

Click Github and paste this: https://www.curseforge.com/minecraft/mc-mods/ocean-world

It will enhance the first impression of your CurseForge page :)

**Comment by Viola-Siemens** [comment]
Thanks for your advice :)
